"""added datetime

Revision ID: 36e4091592c8
Revises: 92abb7394e00
Create Date: 2021-05-26 15:07:55.981998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e4091592c8'
down_revision = '92abb7394e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'expiration_date')
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
