"""added taglines and donations

Revision ID: e01cf51f2b48
Revises: 36e4091592c8
Create Date: 2021-05-27 09:50:06.195711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01cf51f2b48'
down_revision = '36e4091592c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tagline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tagline')
    # ### end Alembic commands ###
